services:
    sme:
        build: .
        network_mode: host
        ports:
            - 0.0.0.0:5002:5002
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        ports:
            - 0.0.0.0:27017:27017
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
version: "3"
