language: csharp
solution: SME_Backend
notifications:
  slack: cgiwave6:1NqbLKzmuRjgH6YOBVndxtwR
    on_success: always
    on_failure: always
mono: none
dotnet: 2.1
script
  - dotnet restore
  - dotnet test SME.Tests